alert("Bem-vindo!"); 
let valora = Number(prompt("informe o valor da A"));
let valorb = Number(prompt("informe o valor da B"));
let valorc = Number(prompt("informe o valor da C"));
let valord = Number(prompt("informe o valor da D"));
let adicao1=(valora+valorb);
let adicao2=(valora+valorc);
let adicao3=(valora+valord);
let adicao4=(valorb+valorc);
let adicao5=(valorb+valord);
let adicao6=(valorc+valord);
let multiplica1=(valora*valorb);
let multiplica2=(valora*valorc);
let multiplica3=(valora*valord);
let multiplica4=(valorb*valorc);
let multiplica5=(valorb*valord);
let multiplica6=(valorc*valord);
alert(`resultado da soma ${adicao1} ${adicao2} ${adicao3} ${adicao4} ${adicao5} ${adicao6}`);
alert(`resultado da multiplição ${multiplica1} ${multiplica2} ${multiplica3} ${multiplica4} ${multiplica5} ${multiplica6}`);